config/routes.rb
Rails.application.routes.draw do

  root to: "homes#top"

  resources :items
  resources :tags
  resources :item_tags,  only: [:index, :create, :destroy]

  #タグで検索
  get "search_tag" => "items#search_tag"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :item_tags, dependent: :destroy
  has_many :ttags, through: :item_tags

  validates :name,:item_text, presence: true



  #編集するとき、タグの入れ替えをする。
    def save_tag(sent_tags)
      unless sent_tags.empty?
        self.item_tags.destroy_all

        sent_tags.each do |new|

          #find_or_create_by 同じ値が存在している場合、既存の値を返す
          #存在しない場合、新しく作成される
          new_post_tag = Ttag.find_or_create_by(tag_name: new)

          #include?で　アイテムにすでに同じタグが関連付けられているかどうかをチェックし、
          #それがない場合にのみ、新しいタグをアイテムに関連付けする
          unless self.ttags.include?(new_post_tag)
            #<<演算子 新しいタグがアイテムに関連付けられ、データベースに保存されます。
            self.ttags << new_post_tag
          end
        end
      end
    end





end

app/models/item_tag.rb
class ItemTag < ApplicationRecord

  belongs_to :ttag
  belongs_to :item

end

app/models/ttag.rb
class Ttag < ApplicationRecord

  has_many :item_tags, dependent: :destroy
  has_many :items, through: :item_tags


  validates :tag_name, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController


  def index
    @items = Item.all
    @tag_list = Ttag.all

  end

  def show
    @item = Item.find(params[:id])
    @item_tags = @item.ttags
  end


  def new
    @item = Item.new
    @tag = Ttag.new
    @tag_list = Ttag.all
  end

  def create
   @item = Item.new

   #@item.name
   @item.name = params[:item][:name]
   @item.item_text = params[:item][:item_text]

   #ビューから取ってきたものを拾ってきている
   #split(nil)は非推奨らしいので、半角スペース
   tag_list = params[:item][:tag_name].split(" ")

    if @item.save!
      @item.save_tag(tag_list)
      redirect_to items_path
    else
      redirect_to new_item_path
    end
  end

  def edit
    @item = Item.find(params[:id])
    #pluck :tag_nameというカラムの値を取得する
    @tags = @item.ttags.pluck(:tag_name).join(" ")
    @tag_list = Ttag.all

  end

  def update
    @item = Item.find(params[:id])
    #フォームから送信されたタグ名のリスト
    tag_list = params[:item][:tag_name].split(" ")

    if @item.update(item_params)
      #save_tagitemモデルで定義
       @item.save_tag(tag_list)
       redirect_to item_path(@item.id)
    else
       redirect_to :edit
    end

  end

  def destroy

    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path

  end


   def search_tag
    #検索結果画面でもタグ一覧表示
    @tag_list = Ttag.all
      #検索されたタグを受け取る
    @tag = Ttag.find(params[:ttag_id])
    #検索されたタグに紐づく投稿を表示
    #byebug
    @items = @tag.items.where(params[:id])
   end



  private

  def item_params
    params.require(:item).permit(:name, :item_text)
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Ttag.all
    @tag = Ttag.new
  end

  def create
   #一度に複数を登録する
   tags = tag_params[:tag_name].split(" ")

    tags.each do |tag|

       #create(カラム名: ブロック変数)

       #find_or_create_by 同じ値が存在する場合、既存のレコードを返し
       #存在しない場合には新しいレコードを作成する
      Ttag.find_or_create_by(tag_name: tag)
    end
   redirect_to tags_path
  end



  def destroy
    @tag = Ttag.find(params[:id])
    @tag.destroy
    redirect_to tags_path
  end


  private

  def tag_params
    params.require(:ttag).permit(:tag_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/homes/top.html.erb
<h1>複数タグの練習　アソシエーションの練習</h1>

<h2>ECサイトを作る。複数タグ付け機能必要。そのための勉強</h2>
<%= link_to "投稿一覧へ", items_path %>
<%= link_to "タグ追加と一覧",tags_path %>





app/views/items/_item_list.html.erb
  <% items.each do |item| %>
  アイテム名:
    <%= link_to item_path(item.id) do %>
      <%= item.name %>
    <% end %>
    <br>
    アイテム説明:<%= item.item_text %><br>

    タグ:

    <%= render "tags/tag_list", tag_list: item.ttags %>

  <% end %>

app/views/items/edit.html.erb
<h1>編集ページ</h1>
<%= link_to "詳細ページ", item_path(@item.id) %><br>

<%= form_with model: @item do |f| %>
  <%= f.text_field :name %>
  <%= f.text_area :item_text %>

  <%= f.text_field :tag_name,value:@tags %>


<%= f.submit "更新" %>
<button id="clear-button" type="button">クリア</button>
<% end %>



<%= render "tags/add_tag", tag_list: @tag_list %>

app/views/items/index.html.erb
<h1>アイテム一覧ページ</h1>

<%= link_to "投稿ページ", new_item_path %>



<h2>アイテム一覧</h2>


  <%= render "item_list", items: @items %>



app/views/items/new.html.erb
<h1>投稿画面</h1>
<%= link_to "トップ画面",root_path %> | <%= link_to "一覧画面",items_path %>

<%= form_with model: @item do |f| %>
<p>タイトル</p>
  <%= f.text_field :name %>

<p>本文</p>
  <%= f.text_area :item_text %>

<p>タグ</p>
 <%= f.text_field :tag_name, placeholder: "タグを複数つけるには空白で区切ってください" %>
<!--タグを保存する時、保存するのは中間テーブル？？-->
  <%= f.submit "投稿" %>
<button id="clear-button" type="button">クリア</button>
<% end %>


<p>タグをクリックすると、フォームに自動で追加されます</p>
<div>

  <%= render "tags/add_tag", tag_list: @tag_list %>

</div>


app/views/items/search_tag.html.erb
<h1>タグ[<%= @tag.tag_name %>]のアイテム一覧</h1>

<div>
  <h2>タグリスト</h2>
<%= render "tags/tag_list", tag_list: @tag_list %>
</div>

<div>
  <h2>アイテム一覧</h2>

  <%= render "item_list",items: @items %>

</div>

<%= link_to "トップ",root_path %>

app/views/items/show.html.erb
<h1>詳細ページ</h1>
<%= link_to "一覧ページ", items_path %><br>

アイテム名: <%= @item.name %><br>
アイテム説明: <%= @item.item_text %><br>
タグ一覧：
<%= render "tags/tag_list", tag_list: @item_tags %>

<%= link_to "削除", item_path(@item), method: :delete %>
<%= link_to "編集", edit_item_path(@item.id) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tag</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tags/_add_tag.html.erb

<% tag_list.each do |tag| %>
  <div><%#= tag_list.tag_name + " " %>

  <%= link_to tag.tag_name, '#', class: 'tag-link' %>
  </div>
<% end %>

app/views/tags/_tag_list.html.erb

<% tag_list.each do |tag_list| %>
 <div>
    <%= link_to tag_list.tag_name,search_tag_path(ttag_id: tag_list.id) %>
    <!--コントローラで、ttag_idを取得して、ブロック変数tag_listのidを表示-->

    <%= "(#{tag_list.items.count})" %>
  </div>
<% end %>

app/views/tags/index.html.erb
<h1>タグ追加と一覧</h1>


<%= link_to "アイテム一覧", items_path %>


<%= form_with model: @tag, url: tags_path do |f| %>
  <%= f.text_field :tag_name %>
  <%= f.submit "投稿" %>

<% end %>


<h2>タグ一覧</h2>
<% @tags.each do |tags| %>
  <%= tags.tag_name %>
  <%= "(#{tags.items.count})" %>
  <%= link_to "x",tag_path(tags.id), method: :delete %>
<% end %>
